# Uncomment this line to define a global platform for your project
platform :ios, '6.0'

target 'Playground' do
pod 'ReactiveCocoa' , '2.0'
end

target 'PlaygroundTests' do

end

target 'PlaygroundUITests' do

end

