# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'HCDReactiveCocoa' do
    pod 'ReactiveCocoa', '~> 2.1.4'
    pod 'libextobjc', '~> 0.3'
    pod '500px-iOS-api', '~> 1.0.5'
    pod 'SVProgressHUD', '~> 0.9'
end

target 'HCDReactiveCocoaTests' do

end

target 'HCDReactiveCocoaUITests' do

end

